INSERT INTO kalturadw.dwh_dim_partners_billing 
(`partner_id` ,
    `partner_group_type_id`,
    updated_at,
    max_monthly_bandwidth_kb ,
    charge_monthly_bandwidth_kb_usd ,
    charge_monthly_bandwidth_kb_unit,
    max_monthly_storage_mb ,
    charge_monthly_storage_mb_usd ,
    charge_monthly_storage_mb_unit ,
    max_monthly_total_usage_mb ,
    charge_monthly_total_usage_mb_usd ,
    charge_monthly_total_usage_mb_unit ,
    max_monthly_entries     ,
    charge_monthly_entries_usd     ,
    charge_monthly_entries_unit     ,
    max_monthly_plays ,
    charge_monthly_plays_usd ,
    charge_monthly_plays_unit,
    max_kusers ,
    charge_kusers_usd ,
    charge_kusers_unit,
    max_publishers ,
    charge_publishers_usd ,
    charge_publishers_unit,
    max_end_users,
    charge_end_users_usd ,
    charge_end_users_unit ,
    class_of_service_id ,
    vertical_id )
SELECT   `partner_id` ,
    `partner_group_type_id`,
    updated_at updated_at,
    max_monthly_bandwidth_kb ,
    charge_monthly_bandwidth_kb_usd ,
    charge_monthly_bandwidth_kb_unit,
    max_monthly_storage_mb ,
    charge_monthly_storage_mb_usd ,
    charge_monthly_storage_mb_unit ,
    max_monthly_total_usage_mb ,
    charge_monthly_total_usage_mb_usd ,
    charge_monthly_total_usage_mb_unit ,
    max_monthly_entries     ,
    charge_monthly_entries_usd     ,
    charge_monthly_entries_unit     ,
    max_monthly_plays ,
    charge_monthly_plays_usd ,
    charge_monthly_plays_unit,
    max_kusers ,
    charge_kusers_usd ,
    charge_kusers_unit,
    max_publishers ,
    charge_publishers_usd ,
    charge_publishers_unit,
    max_end_users,
    charge_end_users_usd ,
    charge_end_users_unit ,
    class_of_service_id ,
    vertical_id
    FROM `kalturadw`.dwh_dim_partners
    WHERE (max_monthly_bandwidth_kb IS NOT NULL AND charge_monthly_bandwidth_kb_usd IS NOT NULL AND charge_monthly_bandwidth_kb_unit IS NOT NULL)
        OR (max_monthly_storage_mb IS NOT NULL AND charge_monthly_storage_mb_usd IS NOT NULL AND charge_monthly_storage_mb_unit IS NOT NULL)
        OR (max_monthly_total_usage_mb IS NOT NULL AND charge_monthly_total_usage_mb_usd IS NOT NULL AND charge_monthly_total_usage_mb_unit IS NOT NULL)
        OR (max_monthly_entries IS NOT NULL AND charge_monthly_entries_usd IS NOT NULL AND charge_monthly_entries_unit IS NOT NULL)
        OR (max_monthly_plays IS NOT NULL AND charge_monthly_plays_usd IS NOT NULL AND charge_monthly_plays_unit IS NOT NULL);
    
 
ALTER TABLE `kalturadw`.dwh_dim_partners
DROP COLUMN    max_monthly_bandwidth_kb ,
DROP COLUMN    charge_monthly_bandwidth_kb_usd ,
DROP COLUMN    charge_monthly_bandwidth_kb_unit,
DROP COLUMN    max_monthly_storage_mb ,
DROP COLUMN    charge_monthly_storage_mb_usd ,
DROP COLUMN    charge_monthly_storage_mb_unit ,
DROP COLUMN    max_monthly_total_usage_mb ,
DROP COLUMN    charge_monthly_total_usage_mb_usd ,
DROP COLUMN    charge_monthly_total_usage_mb_unit ,
DROP COLUMN    max_monthly_entries     ,
DROP COLUMN    charge_monthly_entries_usd     ,
DROP COLUMN    charge_monthly_entries_unit     ,
DROP COLUMN    max_monthly_plays ,
DROP COLUMN    charge_monthly_plays_usd ,
DROP COLUMN    charge_monthly_plays_unit,
DROP COLUMN    max_kusers ,
DROP COLUMN    charge_kusers_usd ,
DROP COLUMN    charge_kusers_unit,
DROP COLUMN    max_publishers ,
DROP COLUMN    charge_publishers_usd ,
DROP COLUMN    charge_publishers_unit,
DROP COLUMN    max_end_users,
DROP COLUMN    charge_end_users_usd ,
DROP COLUMN charge_end_users_unit;

