DROP TABLE IF EXISTS `kalturadw`.dwh_dim_batch_jobs;

CREATE TABLE `kalturadw`.dwh_dim_batch_jobs (
  `batch_job_id` int(11) NOT NULL ,
  `batch_job_type_id` smallint(6) DEFAULT NULL,
  `batch_job_sub_type_id` smallint(6) DEFAULT NULL,
  `data` varchar(4096) DEFAULT NULL,
  `file_size` int(11) DEFAULT NULL,
  `duplication_key` varchar(41) NOT NULL,
  `batch_job_status_id` int(11) DEFAULT NULL,
  `abort` tinyint(4) DEFAULT NULL,
  `check_again_timeout` int(11) DEFAULT NULL,
  `progress` tinyint(4) DEFAULT NULL,
  `message` varchar(1024) DEFAULT NULL,
  `description` varchar(1024) DEFAULT NULL,
  `updates_count` smallint(6) DEFAULT NULL,
   `created_at` DATETIME DEFAULT NULL,
  `created_date_id` INT DEFAULT '-1',
  `created_hour_id` TINYINT DEFAULT '-1',
  `created_by` varchar(20) NOT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `updated_date_id` INT DEFAULT '-1',
  `updated_hour_id` TINYINT DEFAULT '-1',    
  `updated_by` varchar(20) NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_date_id` INT DEFAULT '-1',
  `deleted_hour_id` TINYINT DEFAULT '-1',    
  `priority` tinyint(4) NOT NULL,
  `work_group_id` int(11) NOT NULL,
  `queue_time` datetime DEFAULT NULL,
  `finish_time` datetime DEFAULT NULL,
  `entry_id` varchar(20) DEFAULT NULL,
  `partner_id` int(11) DEFAULT NULL,
  `subp_id` int(11) DEFAULT NULL,
  `scheduler_id` int(11) DEFAULT NULL,
  `worker_id` int(11) DEFAULT NULL,
  `batch_index` int(11) DEFAULT NULL,
  `last_scheduler_id` int(11) DEFAULT NULL,
  `last_worker_id` int(11) DEFAULT NULL,
  `last_worker_remote` int(11) DEFAULT '0',
  `processor_name` varchar(64) DEFAULT NULL,
  `processor_expiration` datetime DEFAULT NULL,
  `parent_job_id` int(11) DEFAULT NULL,
  `processor_location` varchar(64) DEFAULT NULL,
  `execution_attempts` tinyint(4) DEFAULT NULL,
  `lock_version` int(11) DEFAULT NULL,
  `twin_job_id` int(11) DEFAULT NULL,
  `bulk_job_id` int(11) DEFAULT NULL,
  `root_job_id` int(11) DEFAULT NULL,
  `dc` varchar(2) DEFAULT NULL,
  `err_type` int(11) NOT NULL DEFAULT '0',
  `err_number` int(11) NOT NULL DEFAULT '0',
  `on_stress_divert_to` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`batch_job_id`),
  KEY `entry_id_index_id` (`entry_id`,`batch_job_id`),
  KEY `status_job_type_index` (`batch_job_status_id`,`batch_job_type_id`),
  KEY `created_at_job_type_status_index` (`created_at`,`batch_job_type_id`,`batch_job_status_id`),
  KEY `partner_type_index` (`partner_id`,`batch_job_type_id`),
  KEY `partner_id_index` (`partner_id`),
  KEY `work_group_id_index_priority` (`work_group_id`,`priority`),
  KEY `twin_job_id_index` (`twin_job_id`),
  KEY `bulk_job_id_index` (`bulk_job_id`),
  KEY `root_job_id_index` (`root_job_id`),
  KEY `parent_job_id_index` (`parent_job_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8
           