use kalturadw;

DROP TABLE IF EXISTS dwh_hourly_partner_new;
CREATE TABLE `dwh_hourly_partner_new` (
  `partner_id` int(11) NOT NULL DEFAULT '0',
  `date_id` int(11) NOT NULL DEFAULT '0',
  `hour_id` int(11) NOT NULL DEFAULT '0',
  `sum_time_viewed` decimal(20,3) DEFAULT NULL,
  `count_time_viewed` int(11) DEFAULT NULL,
  `count_plays` int(11) DEFAULT NULL,
  `count_loads` int(11) DEFAULT NULL,
  `count_plays_25` int(11) DEFAULT NULL,
  `count_plays_50` int(11) DEFAULT NULL,
  `count_plays_75` int(11) DEFAULT NULL,
  `count_plays_100` int(11) DEFAULT NULL,
  `count_edit` int(11) DEFAULT NULL,
  `count_viral` int(11) DEFAULT NULL,
  `count_download` int(11) DEFAULT NULL,
  `count_report` int(11) DEFAULT NULL,
  `count_media` int(11) DEFAULT NULL,
  `count_video` int(11) DEFAULT NULL,
  `count_image` int(11) DEFAULT NULL,
  `count_audio` int(11) DEFAULT NULL,
  `count_mix` int(11) DEFAULT NULL,
  `count_mix_non_empty` int(11) DEFAULT NULL,
  `count_playlist` int(11) DEFAULT NULL,
  `count_users` int(11) DEFAULT NULL,
  `count_widgets` int(11) DEFAULT NULL,
  `flag_active_site` tinyint(4) DEFAULT '0',
  `flag_active_publisher` tinyint(4) DEFAULT '0',
  `count_buf_start` int(11) DEFAULT NULL,
  `count_buf_end` int(11) DEFAULT NULL,
  `count_open_full_screen` int(11) DEFAULT NULL,
  `count_close_full_screen` int(11) DEFAULT NULL,
  `count_replay` int(11) DEFAULT NULL,
  `count_seek` int(11) DEFAULT NULL,
  `count_open_upload` int(11) DEFAULT NULL,
  `count_save_publish` int(11) DEFAULT NULL,
  `count_close_editor` int(11) DEFAULT NULL,
  `count_pre_bumper_played` int(11) DEFAULT NULL,
  `count_post_bumper_played` int(11) DEFAULT NULL,
  `count_bumper_clicked` int(11) DEFAULT NULL,
  `count_preroll_started` int(11) DEFAULT NULL,
  `count_midroll_started` int(11) DEFAULT NULL,
  `count_postroll_started` int(11) DEFAULT NULL,
  `count_overlay_started` int(11) DEFAULT NULL,
  `count_preroll_clicked` int(11) DEFAULT NULL,
  `count_midroll_clicked` int(11) DEFAULT NULL,
  `count_postroll_clicked` int(11) DEFAULT NULL,
  `count_overlay_clicked` int(11) DEFAULT NULL,
  `count_preroll_25` int(11) DEFAULT NULL,
  `count_preroll_50` int(11) DEFAULT NULL,
  `count_preroll_75` int(11) DEFAULT NULL,
  `count_midroll_25` int(11) DEFAULT NULL,
  `count_midroll_50` int(11) DEFAULT NULL,
  `count_midroll_75` int(11) DEFAULT NULL,
  `count_postroll_25` int(11) DEFAULT NULL,
  `count_postroll_50` int(11) DEFAULT NULL,
  `count_postroll_75` int(11) DEFAULT NULL,
  PRIMARY KEY (`partner_id`,`date_id`,`hour_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY RANGE (date_id)
(PARTITION p_201001 VALUES LESS THAN (20100201) ENGINE = InnoDB)*/;

CALL add_monthly_partition_for_table('dwh_hourly_partner_new');

INSERT INTO dwh_hourly_partner_new
SELECT 	`partner_id`, 
	`date_id`, 
	`hour_id`, 
	`sum_time_viewed`, 
	`count_time_viewed`, 
	`count_plays`, 
	`count_loads`, 
	`count_plays_25`, 
	`count_plays_50`, 
	`count_plays_75`, 
	`count_plays_100`, 
	`count_edit`, 
	`count_viral`, 
	`count_download`, 
	`count_report`, 
	`count_media`, 
	`count_video`, 
	`count_image`, 
	`count_audio`, 
	`count_mix`, 
	`count_mix_non_empty`, 
	`count_playlist`, 
	`count_users`, 
	`count_widgets`, 
	`flag_active_site`, 
	`flag_active_publisher`, 
	`count_buf_start`, 
	`count_buf_end`, 
	`count_open_full_screen`, 
	`count_close_full_screen`, 
	`count_replay`, 
	`count_seek`, 
	`count_open_upload`, 
	`count_save_publish`, 
	`count_close_editor`, 
	`count_pre_bumper_played`, 
	`count_post_bumper_played`, 
	`count_bumper_clicked`, 
	`count_preroll_started`, 
	`count_midroll_started`, 
	`count_postroll_started`, 
	`count_overlay_started`, 
	`count_preroll_clicked`, 
	`count_midroll_clicked`, 
	`count_postroll_clicked`, 
	`count_overlay_clicked`, 
	`count_preroll_25`, 
	`count_preroll_50`, 
	`count_preroll_75`, 
	`count_midroll_25`, 
	`count_midroll_50`, 
	`count_midroll_75`, 
	`count_postroll_25`, 
	`count_postroll_50`, 
	`count_postroll_75`
	FROM 
	`kalturadw`.`dwh_hourly_partner`;

drop table dwh_hourly_partner;
rename table dwh_hourly_partner_new to dwh_hourly_partner;
