rename table kalturadw.dwh_fact_events to kalturadw.dwh_fact_events_old;
rename table kalturadw.dwh_fact_events_new to kalturadw.dwh_fact_events;
rename table kalturadw.dwh_fact_bandwidth_usage to kalturadw.dwh_fact_bandwidth_usage_old;
rename table kalturadw.dwh_fact_bandwidth_usage_new to kalturadw.dwh_fact_bandwidth_usage;
rename table kalturadw.dwh_fact_events_archive to kalturadw.dwh_fact_events_archive_old;
rename table kalturadw.dwh_fact_events_archive_new to kalturadw.dwh_fact_events_archive;
rename table kalturadw.dwh_fact_bandwidth_usage_archive to kalturadw.dwh_fact_bandwidth_usage_archive_old;
rename table kalturadw.dwh_fact_bandwidth_usage_archive_new to kalturadw.dwh_fact_bandwidth_usage_archive;
