/*
SQLyog Community Edition- MySQL Gui
MySQL - 5.1.34-community 
*********************************************************************
*/
/*!40101 SET nameS utf8 */;

create table `kalturadw`.`ri_defaults` (
	`table_name` varchar (300),
	`default_field` varchar (3000),
	`default_value` varchar (3000)
);

insert into `kalturadw`.`ri_defaults` (`table_name`, `default_field`, `default_value`) 
	values
	('dwh_dim_domains','domain_name','CONCAT(a.domain_id, "-Missing Value")'),
	('dwh_dim_kusers','screen_name','"Missing Value"'),
	('dwh_dim_kusers','full_name','"Missing Value"'),
	('dwh_dim_kusers','email','"Missing Value"'),
	('dwh_dim_kusers','location_id','"-1"'),
	('dwh_dim_kusers','country_id','"-1"'),
	('dwh_dim_kusers','gender_id','"-1"'),
	('dwh_dim_kusers','Kuser_status_id','"-1"'),
	('dwh_dim_kusers','created_at','"2099-01-01 00:00:00"'),
	('dwh_dim_kusers','created_date_id','"-1"'),
	('dwh_dim_kusers','created_hour_id','"-1"'),
	('dwh_dim_kusers','updated_at','"2099-01-01 00:00:00"'),
	('dwh_dim_kusers','updated_date_id','"-1"'),
	('dwh_dim_kusers','updated_hour_id','"-1"'),
	('dwh_dim_kusers','partner_id','"-1"'),
	('dwh_dim_entries','kuser_id','"-1"'),
	('dwh_dim_entries','entry_type_id','"-1"'),
	('dwh_dim_entries','entry_Media_type_id','"-1"'),
	('dwh_dim_entries','views','"0"'),
	('dwh_dim_entries','votes','"0"'),
	('dwh_dim_entries','comments','"0"'),
	('dwh_dim_entries','favorites','"0"'),
	('dwh_dim_entries','total_rank','"0"'),
	('dwh_dim_entries','rank','"0"'),
	('dwh_dim_entries','entry_status_id','"-1"'),
	('dwh_dim_entries','entry_media_source_id','"-1"'),
	('dwh_dim_entries','entry_source_id','"-1"'),
	('dwh_dim_entries','entry_license_type_id','"-1"'),
	('dwh_dim_entries','created_at','"2099-01-01 00:00:00"'),
	('dwh_dim_entries','created_date_id','"-1"'),
	('dwh_dim_entries','created_hour_id','"-1"'),
	('dwh_dim_entries','updated_at','"2099-01-01 00:00:00"'),
	('dwh_dim_entries','updated_date_id','"-1"'),
	('dwh_dim_entries','updated_hour_id','"-1"'),
	('dwh_dim_entries','partner_id','"-1"'),
	('dwh_dim_entries','subp_id','"-1"'),
	('dwh_dim_entries','int_id','"-1"'),
	('dwh_dim_entries','moderation_status','"-1"'),
	('dwh_dim_entries','modified_at','"2099-01-01 00:00:00"'),
	('dwh_dim_entries','modified_date_id','"-1"'),
	('dwh_dim_entries','modified_hour_id','"-1"'),
	('dwh_dim_partners','partner_name','"Missing Value"'),
	('dwh_dim_partners','created_at','"2099-01-01 00:00:00"'),
	('dwh_dim_partners','created_date_id','"-1"'),
	('dwh_dim_partners','created_hour_id','"-1"'),
	('dwh_dim_partners','updated_at','"2099-01-01 00:00:00"'),
	('dwh_dim_partners','updated_date_id','"-1"'),
	('dwh_dim_partners','updated_hour_id','"-1"'),
	('dwh_dim_partners','anonymous_kuser_id','"-1"'),
	('dwh_dim_partners','admin_name','"Missing Value"'),
	('dwh_dim_partners','admin_email','"Missing Value"'),
	('dwh_dim_partners','description','"Missing Value"'),
	('dwh_dim_partners','commercial_use','"-1"'),
	('dwh_dim_partners','moderate_content','"-1"'),
	('dwh_dim_partners','notify','"-1"'),
	('dwh_dim_partners','partner_status_id','"-1"'),
	('dwh_dim_partners','partner_status_name','"Missing Value"'),
	('dwh_dim_partners','content_categories','"Missing Value"'),
	('dwh_dim_partners','partner_type_id','"-1"'),
	('dwh_dim_partners','partner_type_name','"Missing Value"'),
	('dwh_dim_partners','adult_content','"-1"'),
	('dwh_dim_partners','partner_package','"-1"'),
	('dwh_dim_ui_conf','ui_conf_type_id','"-1"'),
	('dwh_dim_ui_conf','partner_id','"-1"'),
	('dwh_dim_ui_conf','subp_id','"-1"'),
	('dwh_dim_ui_conf','created_at','"2099-01-01 00:00:00"'),
	('dwh_dim_ui_conf','created_date_id','"-1"'),
	('dwh_dim_ui_conf','created_hour_id','"-1"'),
	('dwh_dim_ui_conf','updated_at','"2099-01-01 00:00:00"'),
	('dwh_dim_ui_conf','updated_date_id','"-1"'),
	('dwh_dim_ui_conf','updated_hour_id','"-1"'),
	('dwh_dim_ui_conf','ui_conf_status_id','"-1"'),
	('dwh_dim_widget','partner_id','"-1"'),
	('dwh_dim_widget','subp_id','"-1"'),
	('dwh_dim_widget','kshow_id','"-1"'),
	('dwh_dim_widget','entry_id','"-1"'),
	('dwh_dim_widget','ui_conf_id','"-1"'),
	('dwh_dim_widget','security_type','"-1"'),
	('dwh_dim_widget','security_policy','"-1"'),
	('dwh_dim_widget','created_at','"2099-01-01 00:00:00"'),
	('dwh_dim_widget','created_date_id','"-1"'),
	('dwh_dim_widget','created_hour_id','"-1"'),
	('dwh_dim_widget','updated_at','"2099-01-01 00:00:00"'),
	('dwh_dim_widget','updated_date_id','"-1"'),
	('dwh_dim_widget','updated_hour_id','"-1"'),
	('dwh_dim_widget_security_policy','widget_security_policy_name','"Missing Value"'),
	('dwh_dim_widget','widget_int_id','"-1"'),
	('dwh_dim_asset_status', 'asset_status_name', '"Missing Value"'),
	('dwh_dim_flavor_pararms','version', '"-1"'),
	('dwh_dim_flavor_pararms','partner_id','"-1"'),
	('dwh_dim_flavor_pararms','name','"Missing Value"'),
	('dwh_dim_flavor_pararms','tags','"Missing Value"'),
	('dwh_dim_flavor_pararms','description','"Missing Value"'),
	('dwh_dim_flavor_pararms','ready_behavior','"-2"'),
	('dwh_dim_flavor_pararms','is_default','"-1"'),
	('dwh_dim_flavor_pararms','formot','"Missing Value"'),
	('dwh_dim_flavor_pararms','video_codec','"Missing Value"'),
	('dwh_dim_flavor_pararms','video_bitrate','"-1"'),
	('dwh_dim_flavor_pararms','audio_codec','"Missing Value"'),
	('dwh_dim_flavor_pararms','audio_bitrate','"Missing Value"'),
	('dwh_dim_flavor_pararms','audio_channels','"Missing Value"'),
	('dwh_dim_flavor_pararms','audio_sample_rate','"-1"'),
	('dwh_dim_flavor_pararms','audio_resolution','"-1"'),
	('dwh_dim_flavor_pararms','width','"-1"'),
	('dwh_dim_flavor_pararms','height','"-1"'),
	('dwh_dim_flavor_pararms','frame_rate','"-1"'),
	('dwh_dim_flavor_pararms','gop_size','"-1"'),
	('dwh_dim_flavor_pararms','two_pass','"-1"'),
	('dwh_dim_flavor_pararms','conversion_engines','"Missing Value"'),
	('dwh_dim_flavor_pararms','conversion_engines_extra_params','"Missing Value"'),
	('dwh_dim_flavor_pararms','view_order','"-1"'),
	('dwh_dim_flavor_pararms','bypass_by_extension','"Missing Value"'),
	('dwh_dim_flavor_pararms','creation_mode','"-1"'),
	('dwh_dim_flavor_pararms','deinterlice','"-1"'),
	('dwh_dim_flavor_pararms','rotate','"-1"'),
	('dwh_dim_flavor_pararms','engine_version','"-1"'),
	('dwh_dim_flavor_pararms','created_at','"2099-01-01 00:00:00"'),
	('dwh_dim_flavor_pararms','updated_at','"2099-01-01 00:00:00"'),
	('dwh_dim_flavor_pararms','deleted_at','"2099-01-01 00:00:00"'),
	('dwh_dim_conversion_profile', 'partner_id', '"-1"'),
	('dwh_dim_conversion_profile', 'name', '"Missing Value"'),
	('dwh_dim_conversion_profile', 'created_at', '"2099-01-01 00:00:00"'),
	('dwh_dim_conversion_profile', 'updated_at', '"2099-01-01 00:00:00"'),
	('dwh_dim_conversion_profile', 'deleted_at', '"2099-01-01 00:00:00"'),
	('dwh_dim_conversion_profile', 'clip_start', '"-1"'),
	('dwh_dim_conversion_profile', 'clip_duration', '"-1"'),
	('dwh_dim_conversion_profile', 'creation_mode', '"-1"'),
	('dwh_dim_flavor_asset','int_id','"-1"'),
	('dwh_dim_flavor_asset','partner_id','"-1"'),
	('dwh_dim_flavor_asset','entry_id','"-1"'),
	('dwh_dim_flavor_asset','flavor_params_id','"-1"'),
	('dwh_dim_flavor_asset','status','"-2"'),
	('dwh_dim_flavor_asset','VERSION','"-1"'),
	('dwh_dim_flavor_asset','width','"-1"'),
	('dwh_dim_flavor_asset','height','"-1"'),
	('dwh_dim_flavor_asset','bitrate','"-1"'),
	('dwh_dim_flavor_asset','frame_rate','"-1"'),
	('dwh_dim_flavor_asset','size','"-1"'),
	('dwh_dim_flavor_asset','is_original','"-1"'),
	('dwh_dim_flavor_asset','created_at','"2099-01-01 00:00:00"'),
	('dwh_dim_flavor_asset','updated_at','"2099-01-01 00:00:00"'),
	('dwh_dim_flavor_asset','deleted_at','"2099-01-01 00:00:00"'),
	('dwh_dim_referrer', 'referrer', 'CONCAT(a.referrer_id, "-Missing Value")'),
	('dwh_dim_locations', 'location_type_name', '"Missing Value"'),
	('dwh_dim_locations', 'location_name', 'CONCAT(a.location_id, " - Missing Value")'),
	('dwh_dim_locations', 'country', '"Missing Value"'),
	('dwh_dim_locations', 'country_id', '"-1"'),
	('dwh_dim_locations', 'country_name', '"Missing Value"'),
	('dwh_dim_locations', 'region', '"Missing Value"'),
	('dwh_dim_locations', 'region_id', '"-1"'),
	('dwh_dim_locations', 'state', '"Missing Value"'),
	('dwh_dim_locations', 'state_id', '"-1"'),
	('dwh_dim_locations', 'city', '"Missing Value"'),
	('dwh_dim_locations', 'dwh_creation_date', '"2099-01-01 00:00:00"'),
	('dwh_dim_locations', 'dwh_update_date', '"2099-01-01 00:00:00"');

