USE kalturadw;
DROP TABLE IF EXISTS `dwh_hourly_partner_innodb`;

CREATE TABLE `dwh_hourly_partner_innodb` (
  `partner_id` INT(11) NOT NULL DEFAULT '0',
  `date_id` INT(11) NOT NULL DEFAULT '0',
  `hour_id` INT(11) NOT NULL DEFAULT '0',
  `sum_time_viewed` DECIMAL(20,3) DEFAULT NULL,
  `count_time_viewed` INT(11) DEFAULT NULL,
  `count_plays` INT(11) DEFAULT NULL,
  `count_loads` INT(11) DEFAULT NULL,
  `count_plays_25` INT(11) DEFAULT NULL,
  `count_plays_50` INT(11) DEFAULT NULL,
  `count_plays_75` INT(11) DEFAULT NULL,
  `count_plays_100` INT(11) DEFAULT NULL,
  `count_edit` INT(11) DEFAULT NULL,
  `count_viral` INT(11) DEFAULT NULL,
  `count_download` INT(11) DEFAULT NULL,
  `count_report` INT(11) DEFAULT NULL,
  `count_media` INT(11) DEFAULT NULL,
  `count_video` INT(11) DEFAULT NULL,
  `count_image` INT(11) DEFAULT NULL,
  `count_audio` INT(11) DEFAULT NULL,
  `count_mix` INT(11) DEFAULT NULL,
  `count_mix_non_empty` INT(11) DEFAULT NULL,
  `count_playlist` INT(11) DEFAULT NULL,
  `count_bandwidth` BIGINT(20) DEFAULT NULL,
  `count_storage` BIGINT(20) DEFAULT NULL,
  `count_users` INT(11) DEFAULT NULL,
  `count_widgets` INT(11) DEFAULT NULL,
  `flag_active_site` TINYINT(4) DEFAULT '0',
  `flag_active_publisher` TINYINT(4) DEFAULT '0',
  `aggr_storage` BIGINT(20) DEFAULT NULL,
  `aggr_bandwidth` BIGINT(20) DEFAULT NULL,
  `count_buf_start` INT(11) DEFAULT NULL,
  `count_buf_end` INT(11) DEFAULT NULL,
  `count_open_full_screen` INT(11) DEFAULT NULL,
  `count_close_full_screen` INT(11) DEFAULT NULL,
  `count_replay` INT(11) DEFAULT NULL,
  `count_seek` INT(11) DEFAULT NULL,
  `count_open_upload` INT(11) DEFAULT NULL,
  `count_save_publish` INT(11) DEFAULT NULL,
  `count_close_editor` INT(11) DEFAULT NULL,
  `count_pre_bumper_played` INT(11) DEFAULT NULL,
  `count_post_bumper_played` INT(11) DEFAULT NULL,
  `count_bumper_clicked` INT(11) DEFAULT NULL,
  `count_preroll_started` INT(11) DEFAULT NULL,
  `count_midroll_started` INT(11) DEFAULT NULL,
  `count_postroll_started` INT(11) DEFAULT NULL,
  `count_overlay_started` INT(11) DEFAULT NULL,
  `count_preroll_clicked` INT(11) DEFAULT NULL,
  `count_midroll_clicked` INT(11) DEFAULT NULL,
  `count_postroll_clicked` INT(11) DEFAULT NULL,
  `count_overlay_clicked` INT(11) DEFAULT NULL,
  `count_preroll_25` INT(11) DEFAULT NULL,
  `count_preroll_50` INT(11) DEFAULT NULL,
  `count_preroll_75` INT(11) DEFAULT NULL,
  `count_midroll_25` INT(11) DEFAULT NULL,
  `count_midroll_50` INT(11) DEFAULT NULL,
  `count_midroll_75` INT(11) DEFAULT NULL,
  `count_postroll_25` INT(11) DEFAULT NULL,
  `count_postroll_50` INT(11) DEFAULT NULL,
  `count_postroll_75` INT(11) DEFAULT NULL,
  `count_streaming` BIGINT(20) DEFAULT '0',
  `aggr_streaming` BIGINT(20) DEFAULT '0'
) ENGINE=INNODB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY RANGE (date_id)
(PARTITION p_201001 VALUES LESS THAN (20100201) ENGINE = INNODB)*/;

CALL kalturadw.add_monthly_partition_for_table('dwh_hourly_partner_innodb');
