CREATE TABLE `kalturadw`.`dwh_dim_access_control` (
  `access_control_id` int(11) NOT NULL,
  `partner_id` int(11) NOT NULL,
  `name` varchar(128) NOT NULL default '',
  `description` varchar(1024) NOT NULL default '',
  `created_at` datetime default NULL,
  `created_date_id` int(11),
  `created_hour_id` tinyint(4),
  `updated_at` datetime default NULL,
  `updated_date_id` int(11),
  `updated_hour_id` tinyint(4),
  `deleted_at` datetime default NULL,
  `deleted_date_id` int(11),
  `deleted_hour_id` tinyint(4),
  `site_restrict_type_id` tinyint(4) default NULL,
  `site_restrict_list` varchar(1024) default NULL,
  `country_restrict_type_id` tinyint(4) default NULL,
  `country_restrict_list` varchar(1024) default NULL,
  `ks_restrict_privilege` varchar(20) default NULL,
  `prv_restrict_privilege` varchar(20) default NULL,
  `prv_restrict_length` int(11) default NULL,
  `kdir_restrict_type` tinyint(4) default NULL,
  PRIMARY KEY  (`access_control_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8