USE kalturadw;

DROP TABLE IF EXISTS dwh_fact_fms_session_events_new;

CREATE TABLE `dwh_fact_fms_session_events_new` (
  `file_id` INT(11) UNSIGNED NOT NULL,
  `line_number` INT(11),
  `event_type_id` TINYINT(3) UNSIGNED NOT NULL,
  `event_category_id` TINYINT(3) UNSIGNED NOT NULL,
  `event_time` DATETIME NOT NULL,
  `event_time_tz` VARCHAR(3) NOT NULL,
  `event_date_id` INT(11) NOT NULL,
  `event_hour_id` TINYINT(3) NOT NULL,
  `context` VARCHAR(100) DEFAULT NULL,
  `entry_id` VARCHAR(20) DEFAULT NULL,
  `partner_id` INT(10) DEFAULT NULL,
  `external_id` VARCHAR(50) DEFAULT NULL,
  `server_ip` VARCHAR(15),
  `server_ip_number` INT(10) UNSIGNED DEFAULT NULL,
  `server_process_id` INT(10) UNSIGNED NOT NULL,
  `server_cpu_load` SMALLINT(5) UNSIGNED NOT NULL,
  `server_memory_load` SMALLINT(5) UNSIGNED NOT NULL,
  `adaptor_id` SMALLINT(5) UNSIGNED NOT NULL,
  `virtual_host_id` SMALLINT(5) UNSIGNED NOT NULL,
  `app_id` TINYINT(3) UNSIGNED NOT NULL,
  `app_instance_id` TINYINT(3) UNSIGNED NOT NULL,
  `duration_secs` INT(10) UNSIGNED NOT NULL,
  `status_id` SMALLINT(3) UNSIGNED DEFAULT NULL,
  `status_desc_id` TINYINT(3) UNSIGNED NOT NULL,
  `client_ip` VARCHAR(15) NOT NULL,
  `client_ip_number` INT(10) UNSIGNED NOT NULL,
  `client_country_id` INT(10) UNSIGNED DEFAULT '0',
  `client_location_id` INT(10) UNSIGNED DEFAULT '0',
  `client_protocol_id` TINYINT(3) UNSIGNED NOT NULL,
  `uri` VARCHAR(4000) NOT NULL,
  `uri_stem` VARCHAR(2000) DEFAULT NULL,
  `uri_query` VARCHAR(2000) DEFAULT NULL,
  `referrer` VARCHAR(4000) DEFAULT NULL,
  `user_agent` VARCHAR(2000) DEFAULT NULL,
  `session_id` VARCHAR(20) NOT NULL,
  `client_to_server_bytes` BIGINT(20) UNSIGNED NOT NULL,
  `server_to_client_bytes` BIGINT(20) UNSIGNED NOT NULL,
  `stream_name` VARCHAR(50) DEFAULT NULL,
  `stream_query` VARCHAR(50) DEFAULT NULL,
  `stream_file_name` VARCHAR(4000) DEFAULT NULL,
  `stream_type_id` TINYINT(3) UNSIGNED DEFAULT NULL,
  `stream_size_bytes` INT(11) DEFAULT NULL,
  `stream_length_secs` INT(11) DEFAULT NULL,
  `stream_position` INT(11) DEFAULT NULL,
  `client_to_server_stream_bytes` INT(10) UNSIGNED DEFAULT NULL,
  `server_to_client_stream_bytes` INT(10) UNSIGNED DEFAULT NULL,
  `server_to_client_qos_bytes` INT(10) UNSIGNED DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY RANGE (event_date_id)
(PARTITION p_20100131 VALUES LESS THAN (20100201) ENGINE = InnoDB,
 PARTITION p_20100228 VALUES LESS THAN (20100301) ENGINE = InnoDB,
 PARTITION p_20100331 VALUES LESS THAN (20100401) ENGINE = InnoDB,
 PARTITION p_20100430 VALUES LESS THAN (20100501) ENGINE = InnoDB,
 PARTITION p_20100531 VALUES LESS THAN (20100601) ENGINE = InnoDB,
 PARTITION p_20100630 VALUES LESS THAN (20100701) ENGINE = InnoDB,
 PARTITION p_20100731 VALUES LESS THAN (20100801) ENGINE = InnoDB,
 PARTITION p_20100831 VALUES LESS THAN (20100901) ENGINE = InnoDB,
 PARTITION p_20100930 VALUES LESS THAN (20101001) ENGINE = InnoDB,
 PARTITION p_20101031 VALUES LESS THAN (20101101) ENGINE = InnoDB,
 PARTITION p_20101130 VALUES LESS THAN (20101201) ENGINE = InnoDB,
 PARTITION p_20101231 VALUES LESS THAN (20110101) ENGINE = InnoDB)*/;

CALL kalturadw.add_daily_partition_for_table('dwh_fact_fms_session_events_new');
