 
INSERT INTO kalturadw_bisources.bisources_ENTRY_TYPE (ENTRY_TYPE_id,ENTRY_TYPE_name) VALUES(7,'LIVE_STREAM');

INSERT INTO kalturadw_bisources.bisources_entry_media_source (ENTRY_MEDIA_SOURCE_id,ENTRY_MEDIA_SOURCE_name) VALUES(29,'AKAMAI_LIVE');

INSERT INTO kalturadw_bisources.bisources_ENTRY_MEDIA_TYPE (ENTRY_MEDIA_TYPE_id,ENTRY_MEDIA_TYPE_name) VALUES(201, 'LIVE_STREAM_FLASH');
INSERT INTO kalturadw_bisources.bisources_ENTRY_MEDIA_TYPE (ENTRY_MEDIA_TYPE_id,ENTRY_MEDIA_TYPE_name) VALUES(202, 'LIVE_STREAM_WINDOWS_MEDIA');
INSERT INTO kalturadw_bisources.bisources_ENTRY_MEDIA_TYPE (ENTRY_MEDIA_TYPE_id,ENTRY_MEDIA_TYPE_name) VALUES(203, 'LIVE_STREAM_REAL_MEDIA');
INSERT INTO kalturadw_bisources.bisources_ENTRY_MEDIA_TYPE (ENTRY_MEDIA_TYPE_id,ENTRY_MEDIA_TYPE_name) VALUES(204, 'LIVE_STREAM_QUICKTIME');